### ISSUE TITLE
transaction-id not handled correctly

### ISSUE THREAD

**Issue by JavaLudwig** [rockcarver/frodo-cli#105] opened 2022-10-21 19:37 UTC
## Frodo CLI version
`frodo -v`

You seem to be running the binary package
Installed versions:
cli: v0.18.1
lib: v0.16.1
node: v18.5.0

## Describe the issue
Execution of for example

`frodo logs fetch -b "2022-10-20T12:45:00Z" -e "2022-10-20T13:15:00Z" -l FINER -c am-everything,idm-everything -t "1666270841886-82506d3b86da2a81c7fe-305690/0" xyz`

reports 

`fetch ERROR: fetch data error - TypeError: Cannot read properties of undefined (reading 'includes')
`

**Comment by atomicsamurai** [comment] 2022-10-24 21:44
Duplicate of rockcarver/frodo-lib#137

**Closed** 2022-11-18 16:00 UTC
Labels: bug
