### ISSUE TITLE
extract scripts when importing

### ISSUE THREAD

**Issue by meesvandongen** [rockcarver/frodo-cli#205] opened 2022-12-06 08:27 UTC
A new option, `-x --extract`, which would extract scripts to separate files. Affected are any commands that export (and import) scripts, such as `frodo script` and `frodo idm` (e.g. onCreate scripts). The export result could look like this:
- `my-script-name.script.js`
- `my-script-name.meta.json`

Where `my-script-name.meta.json` would refer to a `.script.js` file for relevant fields.

Use case is being more easily able to edit scripts locally.

It would require some kind of abstraction to handle scripts in every possible file. Next to this, files with multiple scripts should be handled. Furthermore, different languages should be taken into account (groovy, js).

Is this something you would be interested in? I will be able to make a PR.

**Comment by vscheuber** [comment] 2023-02-15 16:21
Duplicate of #52

**Closed by vscheuber** 2023-02-15 16:21 UTC
Labels: enhancement
